version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./prisma:/home/node/app/prisma
      - ./package.json:/home/node/app/package.json
      - ./pnpm-lock.yaml:/home/node/app/pnpm-lock.yaml
    expose:
      - "3333"
    ports:
      - "3333:3333"
    env_file:
      - ./.env
    command: ["sh", "-c", "pnpm prisma migrate deploy && pnpm dev"]
    depends_on:
      database:
        condition: service_healthy
    restart: always
    networks:
      - my-network

  database:
    container_name: postgres
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data: