version: "3"

services:

  base-api: &base-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./prisma:/home/node/app/prisma
      - ./package.json:/home/node/app/package.json
      - ./pnpm-lock.yaml:/home/node/app/pnpm-lock.yaml

  api:
    container_name: api
    <<: *base-api
    ports:
      - "3333:3333"
    env_file:
      - ./.env
    command: ["sh", "-c", "pnpm prisma migrate deploy && pnpm dev"]
    depends_on:
      database:
        condition: service_healthy
    restart: always

  api-test:
    container_name: api-test
    <<: *base-api
    ports:
      - "3334:3334"
    env_file:
      - ./.env.test
    command: ["sh", "-c", "pnpm prisma migrate deploy && pnpm dev & sleep 3 && pnpm test:e2e"]
    depends_on:
      database-test:
        condition: service_healthy
    restart: always

  database:
    container_name: postgres
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10

  database-test:
    container_name: postgres-test
    image: postgres:16
    ports:
      - 5433:5432
    env_file:
      - ./.env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  postgres_data: